apiVersion: v1
kind: ServiceAccount
metadata:
   name: dex
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dex-role
rules:
  - apiGroups: ["dex.coreos.com"] # API group created by dex
    resources: ["*"]
    verbs: ["*"]
    nonResourceURLs: []
  - apiGroups: ["apiextensions"]
    resources: ["thirdpartyresources"]
    verbs: ["create"] # To manage its own resources identity must be able to create thirdpartyresources.
    nonResourceURLs: []
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dex-role-binding
subjects:
- kind: ServiceAccount
  name: dex                 # Service account assigned to the dex pod.
  namespace: default # The namespace dex is running in.
roleRef:
  kind: ClusterRole
  name: dex-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
data:
  config.yaml: |
    issuer: https://dex.sandbox.yld.io
    storage:
      type: postgres
      config:
        host: authentication-db-postgresql.authentication.svc.cluster.local
        database: dex_db
        user: dex
        password: testy123
        ssl:
          mode: disable
    # storage:
    #   type: kubernetes
    #   config:
    #     inCluster: true
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        # TODO(tomgco) Move to k8s secrets
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://dex.sandbox.yld.io/callback
        orgs:
        - name: yldio
          teams:
            - devops
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticClients:
    - id: k8s-auth
      redirectURIs:
      - 'https://dex.sandbox.yld.io/callback'
      - 'http://k8s-auth.sandbox.yld.io/callback'
      name: 'Kubernetes authentication'
      # TODO(tomgco) Move to k8s secrets
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    expiry:
       signingKeys: "30s"
       idTokens: "1m"
    logger:
      level: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
spec:
  selector:
    app: dex
  ports:
  - protocol: TCP
    port: 443
    targetPort: 5556
  type: LoadBalancer
